language: smalltalk
sudo: false

os:
  - linux

env:
  - GSCI_CLIENTS="Pharo-5.0" GSCI_DEVKIT_BRANCH="dev_tode"

smalltalk:
  - GemStone-3.3.0
  
smalltalk_config: .smalltalk.ston

cache:
  directories:
    - $SMALLTALK_CI_CACHE
